# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Karlsson
email: robert.eg.karlsson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Developer blog written by Robert Karlsson.
  Posts about Front End stuff and iOS development with Swift.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: date
url: "https://robertkarlsson.github.io" # the base hostname & protocol for your site
twitter_username: bobanovskii
github_username:  robertkarlsson
linkedin_username:

# Build settings
markdown: kramdown
